steps:
  # 1. Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cgn-wiki:$SHORT_SHA'
      - '.'

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cgn-wiki:$SHORT_SHA'

  # 3. Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cgn-wiki'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cgn-wiki:$SHORT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

substitutions:
  _REGION: us-central1
  _REPO_NAME: app-images

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cgn-wiki:$SHORT_SHA'
